#!/bin/sh
# .bashrc
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

#grep命令高亮命中的词
alias grep="grep --color=auto"
# User specific aliases and functions

export LANG=zh_CN.utf-8
export PS1="\[\e[36;1m\]\A [\H] \u@\[\e[machine-color;1m\]machine-ip \w> \[\e[0m\]"

#文件创建的权限.同组也可以进行修改
umask 002

ulimit -n 30000

#输出错误和成功信息的函数,带底色
function error(){ echo  -e "\033[41;36m $1 \033[0m";}
function ok(){ echo  -e "\033[42;30m $1 \033[0m";}


